[build-system]
requires = [
    "setuptools",
    "wheel",
    # TODO: Latest setuptools_scm requires Python >=3.7
    # Version restriction can be removed after Python update
    "setuptools_scm<7"
]
build-backend = "setuptools.build_meta"
